let randomSon = Math.round(Math.random() * 100)
alert("hozir sizda random sonlar chiqadi")
alert(`Sizga random orqali chiqagan son: ${randomSon}`)
let tastiq = confirm("random sonini 2ga bolmoqchimisiz yoki kopaytirmoqchimisiz?")
alert(`Sizga random orqali tushgan son: ${randomSon}  \n bu sonni biz 2ga bolganimzda: ${randomSon / 2}  \n bu sonnni 2ga kopaytirganimzda: ${randomSon * 2} chiqdi \n bu sonni biz qoldiqli bn bolganimzda : ${randomSon % 2} chiqdi`)
